# Generated by Django 5.1.7 on 2025-04-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('stat_type', models.CharField(choices=[('sales', 'Sales'), ('orders', 'Orders'), ('deliveries', 'Deliveries'), ('customers', 'Customers'), ('products', 'Products'), ('inventory', 'Inventory')], max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dashboard Statistic',
                'verbose_name_plural': 'Dashboard Statistics',
                'ordering': ['stat_type', 'period'],
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('order', 'Order'), ('delivery', 'Delivery'), ('inventory', 'Inventory'), ('user', 'User'), ('store', 'Store'), ('product', 'Product')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Recent Activity',
                'verbose_name_plural': 'Recent Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
